config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end
 
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root to: "users#index"
    resources :comments,only: [:index, :destroy] 
    resources :posts,only: [:index, :destroy] 
    resources :users,only: [:index]
  end

  scope module: :user do
    root to: "homes#top"
    resources :users,only: [:show, :edit, :update] do
      collection do
          patch :withdrow
          get   :complete
      end 
    end
    resources :posts,only: [:index, :show, :new, :create, :destroy] do
      resources :comments,only: [:create, :destroy], shallow: true do 
        collection do
          get :favorite
        end
         resources :comment_favorites,only: [:create, :destroy] 
      end
      collection do
          get :favorite
          get :my_post
          get "other_user/:id", to: "posts#other_user", as: :other_user
      end
      resource :favorites,only: [:create, :destroy]
    end
    resources :favorites,only: [:create, :destroy]
  end
  
  get "/user/search" => "user/searches#search"
  get "/user/information/edit" => "user/users#edit"
  get "/user/mypage" => "user/users#show"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord
  #TODO: アソシエーション
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorit_users, through: :favorites, source: :user
  
  #TODO: 公開・非公開機能
  #TODO: scope :is_published_flag, -> {where(is_published_flag: 1)}
  #TODO: scope :is_published_flag, -> {where(is_published_flag: 0)}
  enum is_published_flag: { published: 0, unpublished: 1 }
  #TODO: バリデーション
  validates :body, presence: true
  validates :is_published_flag, presence: true
  
  #TODO: いいね機能
  #TODO: ユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べる
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  #TODO: 検索機能
  #TODO: selfはモデル名（メソッドが記述されているモデルを表す）
  def self.search_for(content)
  #TODO: 完全一致
  #if method == 'perfect'
    #Post.where(body: content)
  #TODO: 前方一致
  #elsif method == 'forward'
    #Post.where('body LIKE ?', content+'%')
  #TODO: 後方一致
  #elsif method == 'backward'
    #Post.where('body LIKE ?', '%'+content)
  #else
  #TODO: 部分一致
  #TODO: LIKE句 カラム名、LIKE、？, 右にWord, 右のWordが？代入
  #TODO: %は全ての文字
    Post.where('body LIKE ?', '%'+content+'%')
  #end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  def self.guest
    find_or_create_by!(name: 'guestuser' ,email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guestuser"
      user.telephone_number = "08088888888"
      
    end
  end
  
  has_one_attached :image
  #TODO: アソシエーション
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post
  has_many :comment_favorites, dependent: :destroy
  #TODO: バリデーション
  validates :name, presence: true
  validates :telephone_number, presence: true
  validates :email, presence: true
  
  def get_profile_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
  #TODO: selfはモデル名（メソッドが記述されているモデルを表す）
  def self.search_for(content)
    #TODO: 完全一致
    #if method == 'perfect'
      #Post.where(body: content)
    #TODO: 前方一致
    #elsif method == 'forward'
      #Post.where('body LIKE ?', content+'%')
    #TODO: 後方一致
    #elsif method == 'backward'
      #Post.where('body LIKE ?', '%'+content)
    #else
    #TODO: 部分一致
    #TODO: LIKE句 カラム名、LIKE、？, 右にWord, 右のWordが？代入
    #TODO: %は全ての文字
    User.where('name LIKE ?', '%' + content + '%')
  end
  
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  
  before_action :authenticate_admin!
  
  def index
    @posts = Post.all
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to admin_posts_path
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  
  before_action :authenticate_admin!
  
  
  def index
    @users = User.all
  end
end

app/controllers/user/comment_favorites_controller.rb
class User::CommentFavoritesController < ApplicationController
  def create
    comment = Comment.find(params[:comment_id])
    favorite = current_user.comment_favorites.new(comment_id: comment.id)
    favorite.save
    redirect_to post_path(comment.post)
  end
  
  def destroy
    comment = Comment.find(params[:id])
    favorite = current_user.comment_favorites.find_by(comment_id: comment.id)
    favorite.destroy
    redirect_to post_path(comment.post)
  end
end

app/controllers/user/comments_controller.rb
class User::CommentsController < ApplicationController
  
  def create
    #TODO: コメント投稿
    post = Post.find(params[:post_id])
    comment = current_user.comments.new(comment_params)
    comment.post_id = post.id
    comment.save
    redirect_to post_path(post)
  end
  
  def destroy
    #TODO: コメント削除
    Comment.find(params[:id]).destroy
    redirect_to post_path(params[:post_id])
  end
  
  def favorite
    @favorite_posts = current_user.favorited_posts
  end

  private
   
  def comment_params
    params.require(:comment).permit(:user_id, :post_id, :comment)  
  end
  
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/favorites_controller.rb
class User::FavoritesController < ApplicationController
  
  def create
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.new(post_id: post.id)
    favorite.save
    redirect_to posts_path(post)
  end
  
  def destroy
    post = Post.find(params[:post_id])
    favorite = current_user.favorites.find_by(post_id: post.id)
    favorite.destroy
    redirect_to posts_path(post)
  end
  
  
  
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController
  #before_action :authenticate_user!
  
  def top
    
  end
  
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/posts_controller.rb
class User::PostsController < ApplicationController
  
  before_action :authenticate_user!
  
  def index
    #TODO: 皆の投稿表示画面
    @posts = Post.all
    @user = current_user
    #TODO: 公開された記事のみ表示
    @posts = Post.published
  end
  
  def favorite
    #TODO: いいね画面
    @favorite_posts = current_user.favorited_posts
  end
  
  def my_post
    #TODO: 自分の投稿表示画面
    @post = current_user.posts
  end
  
  def other_user
    #TODO: ほかのユーザの投稿表示画面
    @user = User.find(params[:id])
    @posts = @user.posts.published
  end
  
  def new
    #TODO: 新規投稿
    @user = current_user
    @post = Post.new
  end
  
  def show
    #TODO: コメント投稿画面・投稿詳細画面
    @post = Post.find(params[:id])
    @user_tag = User.find(params[:id])
    @user = current_user
    @comment = Comment.new
    @posts = Post.published
  end
  
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    #TODO: 対象のカラムにデータが入力されていればsaveメソッドでtrueが返される
    if @post.save
      redirect_to posts_path
    #TODO: 対象のカラムにデータが入力されていなければ、saveメソッドでfalseが返される
    else
      render :new
    end
    @post.is_published_flag = post_params[:is_published_flag]
  end
  
  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end
  
  private
  
  #def set_user
   # @user = User.find(params[:id])
  #end
   
  def post_params
    params.require(:post).permit(:user_id, :body, :is_published_flag)  
  end
  
  def ensure_correct_user
    @post = Post.find(params[:id])
    unless @post.user == current_user
      redirect_to posts_path 
    end
  end
  
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  
  def after_sign_in_path_for(resource)
     posts_path
  end

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end
  
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name, :telephone_number])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/searches_controller.rb
class User::SearchesController < ApplicationController
  before_action :authenticate_user!
 
  def search
  	#TODO: paramsでmodel,contentをうけとる
    @model = params[:model]
    #TODO: ||= '' nilガード
    #TODO: params[:content]がなかったら、''をいれる
		@content = params[:content] #||= ''
		#TODO: コンテンツが空っだたら
		if params[:content].blank?
		#TODO: メッセージを表示する
			@message = "検索にはキーワードをいれてください"
		#TODO:　returnは処理ここで終了する
			return
		end
		#TODO: modelがuserだったら
		if @model == 'user'
		#TODO: userのmodelはとぶ
			@users = User.search_for(@content)
		else
			@posts = Post.search_for(@content)
		end
  end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  #before_action :configure_sign_in_params, only: [:create]
  before_action :user_state, only: [:create]
  
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  def after_sign_in_path_for(resource)
    posts_path
  end
  
  def after_sign_out_path_for(resource)
    root_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to posts_path(user), notice: 'guestuserでログインしました。'
  end
  
  def user_state
  ## 【処理内容1】 入力されたemailからアカウントを1件取得
  @user = User.find_by(email: params[:user][:email])
  ## アカウントを取得できなかった場合、このメソッドを終了する
  return if !@user
  ## 【処理内容2】 取得したアカウントのパスワードと入力されたパスワードが一致してるかを判別
    if @user.valid_password?(params[:user][:password])
      ## 【処理内容3】
      if @user.is_deleted == true
          redirect_to  new_user_registration_path
      end
    end
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController
  
  before_action :authenticate_user!
  before_action :ensure_guest_user, only: [:edit]
  
  def show
    # マイページ
    @user = current_user
  end

  def edit
    # マイページ編集画面
    unless @user == current_user
     redirect_to  user_mypage_path(@user)
    end
  end
  
  def update
    # 編集更新
    @user = current_user
    if current_user.update(user_params)
      flash[:notice] = "「 更新しました 」"
      redirect_to user_mypage_path(@user)
    else
      flash[:notice] = "「 更新できませんでした 」"
      redirect_to user_information_edit_path(@user)
    end
  end

  def complete
    # アカウント削除画面
    @user = current_user
  end
  
  def withdrow
    # アカウント削除実行
    @user = current_user
    @user.update(is_deleted: true)
    flash[:notice] = "本当に削除してもよろしいですか？"
    reset_session
    redirect_to new_user_registration_path
  end
  
   private
  
  def user_params
    params.require(:user).permit(:email, :name, :telephone_number, :is_deleted, :image)  
  end
  
  def ensure_guest_user
    @user = current_user
    if @user.name == "guestuser"
      redirect_to  user_mypage_path, notice: 'ゲストユーザーはプロフィール編集画面へ遷移できません。'
    end
  end  
  
  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_mypage_path(current_user)
    end
  end
  
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/user/comment_favorites_helper.rb
module User::CommentFavoritesHelper
end

app/helpers/user/comments_helper.rb
module User::CommentsHelper
end

app/views/user/posts/_search_post.html.erb
<p id="notice"></p>
<div class="container">
  <div class="mb-4"><h2>Search</h2></div>
  <%= @message %>
  <% if @posts.present? %>
  <% @posts.each do |item| %>
    <div class="row card-shadow w-75">
      <div class="col-2">
        <%= link_to post_path(item.id) do %>
        <%= image_tag item.user.image, size: "50x50" %>
        <% end %>
      </div>
      <div class="col-8">
        <div class="row">
          <div class="col font-weight-bold"><%= item.user.name %></div>
          <div class="col"><time><%= l DateTime.current, format: :short %></time></div>
          <div class="col">
            <% if @post == current_user %>
            <%= link_to "削除", post_path(item.id), method: :delete %>
            <% end %>
          </div>
        </div>
        <div><%= item.body %></div>
        <div class="row">
          <div class="col">
            <%= link_to post_path(item.id) do %>
              <i class="fa-regular fa-comment"></i>
            <% end %>
          </div>
          <div class="col">
            
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% end %>
</div>

app/views/user/posts/_tem_post.html.erb
<p id="notice"></p>
<div class="container">
  <% post.each do |item| %>
    <div class="row card-shadow w-75">
      <div class="col-2">
        <%= link_to post_path(item.id) do %>
        <%= image_tag item.user.image, size: "80x80" %>
        <% end %>
      </div>
      <div class="col-8">
        <div class="row">
          <div class="col font-weight-bold"><%= item.user.name %></div>
          <div class="col"><time><%= l DateTime.current, format: :short %></time></div>
          <div class="col"><%= link_to "削除", post_path(item.id), method: :delete %></div>
        </div>
        <div><%= item.body %></div>
        <div class="row">
          <div class="col">
            <%= link_to post_path(item.id) do %>
              <i class="fa-regular fa-comment"></i>
            <% end %>
          </div>
          <div class="col">
            
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/user/posts/favorite.html.erb
<p id="notice"></p>
<div class="container">
  <div class="mb-4"><h2>Favorite</h2></div>
    <% @favorite_posts.each do |item| %>
    <div class="row card-shadow w-75">
      <div class="col-2">
        <%= link_to other_user_posts_path(item.user.id) do %>
          <%= image_tag item.user.image, size: "80x80" %>
        <% end %>
      </div>
      <div class="col-8">
        <div class="row">
          <div class="col font-weight-bold"><%= item.user.name %></div>
          <div class="col"><time><%= l DateTime.current, format: :short %></time></div>
          <div class="col"></div>
        </div>
        <div><%= item.body %></div>
        <div class="row">
          <div class="col">
            <%= link_to post_path(item.id) do %>
              <i class="fa-regular fa-comment"></i>
            <% end %>
          </div>
          <div class="col">
            <!--いいね機能-->
            <% if item.favorited_by?(current_user) %>
              <p>
                <%= link_to post_favorites_path(item), method: :delete do %>
                  ♥<%= item.favorites.count %>
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to post_favorites_path(item), method: :post do %>
                  ♡<%= item.favorites.count %>
                <% end %>
              </p>
              <% end %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/user/posts/index.html.erb
<p id="notice"></p>
<div class="container">
  <div><%= flash[:notice] %></div>
  <div class="mb-4"><h2>Home</h2></div>
  <% if @posts.present? %>
  <!--@postが存在すればtrue-->
      <% @posts.each do |item| %>
        <div class="row card-shadow w-75">
          <div class="col-2">
            <!--アイコン表示-->
            <%= link_to other_user_posts_path(item.user.id) do %>
            <%= image_tag item.user.get_profile_image(200,200), size: "80x80" %>
            <% end %>
          </div>
          <div class="col-8">
            <div class="row">
              <div class="col font-weight-bold"><%= item.user.name %></div>
              <div class="col"><time><%= l DateTime.current, format: :short %></time></div>
              <div class="col">
                <!--ログインしているユーザ以外には表示されない-->
                <% if item.user == current_user %>
                  <%= link_to "削除", post_path(item.id), method: :delete %>
                <% end %>
              </div>
            </div>
            <div><%= item.body %></div>
            <div class="row">
              <div class="col">
                <!--コメントアイコンから詳細画面へ-->
                <%= link_to post_path(item.id) do %>
                  <i class="fa-regular fa-comment"></i>
                <% end %>
              </div>
              <!--いいね機能-->
              <div class="col">
                <% if item.favorited_by?(current_user) %>
              <p>
                <%= link_to post_favorites_path(item), method: :delete do %>
                  ♥<%= item.favorites.count %>
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to post_favorites_path(item), method: :post do %>
                  ♡<%= item.favorites.count %>
                <% end %>
              </p>
              <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  <% end %>
</div>

app/views/user/posts/my_post.html.erb
<p id="notice"></p>
<div class="container">
<div class="mb-4 "><h2>My post</h2></div>
    <% @post.each do |item| %>
      <div class="row card-shadow w-75">
        <div class="col-2">
          <%= image_tag item.user.get_profile_image(200,200), size: "80x80" %>
        </div>
        <div class="col-8">
          <div class="row">
            <div class="col font-weight-bold"><%= item.user.name %></div>
            <div class="col"><time><%= l DateTime.current, format: :short %></time></div>
            <div class="col"><%= link_to "削除", post_path(item.id), method: :delete %></div>
          </div>
          <div><%= item.body %></div>
          <div class="row">
            <div class="col">
              <%= link_to post_path(item.id) do %>
                <i class="fa-regular fa-comment"></i>
              <% end %>
            </div>
            <!--いいね機能-->
            <div class="col">
              <% if item.favorited_by?(current_user) %>
            <p>
              <%= link_to post_favorites_path(item), method: :delete do %>
                ♥<%= item.favorites.count %>
              <% end %>
            </p>
            <% else %>
            <p>
              <%= link_to post_favorites_path(item), method: :post do %>
                ♡<%= item.favorites.count %>
              <% end %>
            </p>
            <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/user/posts/new.html.erb
<p id="notice"></p>
<div class="container">
  
  <!--#TODO: バリデーション-->
    <% if @post.errors.any? %>
      <%= @post.errors.count %>件のエラーが発生しました
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    <% end %>
    
    
      <div class="row justify-content-center mb-4"><h2>New post</h2></div>
      <div class="row justify-content-center">
        <div class="col-2">
          <%= image_tag @user.get_profile_image(200,200), size: "80x80" %>
        </div>
        <div>
          <%= form_with model: @post, url: '/posts', local: true do |f| %>
          <div class="row">
            <div class="col">
              <!--#TODO:公開・非公開の選択-->
              <%#= f.select :is_published_flag, Post.is_published_flag.keys.to_a, {}, { class:'item-open' } %>
              
              <%= f.radio_button :is_published_flag, Post.is_published_flags.key(0) %>
              <%= f.label :is_published_flag_published, Post.is_published_flags_i18n[:published] %>
              <%#= f.label :is_published_flag, "公開" %>
              <%#= f.radio_button :is_published_flag, 1 %>
            </div>
            <div class="col">
              <%= f.radio_button :is_published_flag, Post.is_published_flags.key(1) %>
              <%= f.label :is_published_flag_unpublished, Post.is_published_flags_i18n[:unpublished] %>
              <%#= f.label :is_published_flag, "非公開" %>
              <%#= f.radio_button :is_published_flag, 0 %>
            </div>
          </div>
          <div class="col my-3"><%= f.text_area :body %></div>
          <div class="col"><%= f.submit 'Post', class:"btn btn-primary" %></div>
        </div>
        <% end %>
    </div>
    
</div>

app/views/user/posts/other_user.html.erb
<p id="notice"></p>
<div class="container">
    <div class="row card-shadow w-75">
      <div class="col-2">
        <%= image_tag @user.get_profile_image(200,200), size: "80x80" %>
      </div>
      <div class="col-8">
        <div class="row">
          <div class="col font-weight-bold"><%= @user.name %></div>
          <div class="col"><time><%= l DateTime.current, format: :short %></time></div>
          <div class="col"></div>
        </div>
      <% if @posts.present? %>
        <% @posts.each do |item| %>
          <div><%= item.body %></div>
          <div class="row">
            <div class="col">
              <%= link_to post_path(item.id) do %>
                <i class="fa-regular fa-comment"></i>
              <% end %>
            </div>
            <div class="col">
              <% if item.favorited_by?(current_user) %>
              <p>
                <%= link_to post_favorites_path(item), method: :delete do %>
                  ♥<%= item.favorites.count %>
                <% end %>
              </p>
              <% else %>
              <p>
                <%= link_to post_favorites_path(item), method: :post do %>
                  ♡<%= item.favorites.count %>
                <% end %>
              </p>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>
      </div>
    </div>
</div>

app/views/user/posts/show.html.erb
<p id="notice"></p>
<div class="container">
  <div class="row card-shadow w-75">
      <div class="col-2">
        <%= image_tag @user_tag.get_profile_image(200,200), size: "80x80" %>
      </div>
      <div class="col-8">
        <div class="row">
          <div class="col font-weight-bold"><%= @post.user.name %></div>
          <div class="col"><time><%= l DateTime.current, format: :short %></time></div>
          <div></div>
        </div>
          <div><%= @post.body %></div>
          <!--投稿のいいね機能-->
          <% if @post.favorited_by?(current_user) %>
          <p>
            <%= link_to post_favorites_path(@post), method: :delete do %>
              ♥<%= @post.favorites.count %>
            <% end %>
          </p>
          <% else %>
          <p>
            <%= link_to post_favorites_path(@post), method: :post do %>
              ♡<%= @post.favorites.count %>
            <% end %>
          </p>
          <% end %>
      </div>
  </div>
    
    <!--コメント表示-->
    <% if @post.comments.present? %>
      <% @post.comments.each do |comment| %>
        <div class="row card-shadow w-75 ml-3">
          <div class="col-2">
            <%= image_tag comment.user.get_profile_image(200,200), size: "80x80" %>
          </div>
          <div class="col-8">
            <div class="row">
              <div class="col font-weight-bold"><%= comment.user.name %></div>
              <div class="col"><time><%= l DateTime.current, format: :short %></time></div>
              <div class="col">
                <% if comment.user == current_user %>
                  <%= link_to "削除", comment_path(comment, post_id: comment.post.id), method: :delete %>
                <% end %>
              </div>
            </div>
           <!--コメントのいいね-->
            <div><%= comment.comment %></div>
                <% if comment.favorited_by?(current_user) %>
                  <p>
                    <%= link_to comment_favorite_path(comment), method: :delete do %>
                      ♥<%= comment.comment_favorites.count %>
                    <% end %>
                  </p>
                  <% else %>
                  <p>
                    <%= link_to comment_comment_favorites_path(comment), method: :post do %>
                      ♡<%=comment.comment_favorites.count %>
                    <% end %>
                  </p>
                <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>

<!--コメント投稿-->
<%= form_with model: [@post, @comment] do |f| %>
  <div class="col card-shadow w-75 ml-5">
      <div class="col-2"></div>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに", class: "mt-3" %>
    <%= f.submit "送信する" %>
  </div>
<% end %>