config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
    post 'users/guest_sign_in', to: 'user/sessions#guest_sign_in'
  end
 
  devise_for :users,skip: [:passwords], controllers: {
  registrations: "user/registrations",
  sessions: 'user/sessions'
}

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

  namespace :admin do
    root to: "users#index"
    resources :comments,only: [:index, :destroy] 
    resources :posts,only: [:index, :destroy] 
    resources :users,only: [:index]
  end

  scope module: :user do
    root to: "homes#top"
    resources :users,only: [:show, :edit, :update] do
      collection do
          patch :withdrow
          get   :complete
      end 
    end
    resources :posts,only: [:index, :show, :new, :create, :destroy] do
      resources :comments,only: [:create, :destroy], shallow: true do 
        collection do
          get :favorite
        end
         resources :comment_favorites,only: [:create, :destroy] 
      end
      collection do
          get :favorite
          get :my_post
          get "other_user/:id", to: "posts#other_user", as: :other_user
      end
      resource :favorites,only: [:create, :destroy]
    end
    resources :favorites,only: [:create, :destroy]
  end
  
  get "/user/search" => "user/searches#search"
  get "/user/information/edit" => "user/users#edit"
  get "/user/mypage" => "user/users#show"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LifeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/06d5403368.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          
          <div class="col-3">
            <a class="navbar-brand" href="/"><%= image_tag 'Life.jpg', size: '80x80' %></a>
          </div>
          <div class="col-4">
            
            <%= render 'user/searches/form' %>
          </div>
          <div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
          </div>
          <div class="collapse navbar-collapse col-4" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
          
            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to  user_mypage_path, class: 'nav-link' do %>
                  <i class="fas fa-user" aria-hidden="true"></i>Mypage
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_post_path, class: 'nav-link' do %>
                  <i class="fas fa-plus" aria-hidden="true"></i>New
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to "Log-out", destroy_user_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% elsif admin_signed_in? %>
              <li class="nav-item">
                <%= link_to "ユーザ", admin_root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "コメント", admin_comments_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "投稿", admin_posts_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link' %>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to "Top", root_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Sign-up", new_user_registration_path, class: 'nav-link' %>
              </li>
              <li class="nav-item">
                <%= link_to "Log-in", new_user_session_path, class: 'nav-link' %>
              </li>
            <% end %>
          </ul>
          </div>
          
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <%= yield %>
    </main>
    <footer class="footer ">
      <div class="container">
        <ul class = "d-flex justify-content-center align-self-center mb-0 shadow p-3 mb-5 bg-white rounded">
        <% if user_signed_in? %>
                <li>
                  <%= link_to posts_path, class: 'nav-link text-secondary' do %>
                    <i class="fas fa-home" aria-hidden="true"></i> Home
                  <% end %>
                </li>
                <li>
                  <%= link_to favorite_posts_path(), class: 'nav-link text-secondary' do %>
                    <i class="fas fa-heart" aria-hidden="true"></i> Fovorite
                  <% end %>
                </li>
                <li>
                  <%= link_to my_post_posts_path, class: 'nav-link text-secondary' do %>
                    <i class="fas fa-user-circle" aria-hidden="true"></i> My Post
                  <% end %>
                </li>
        <% end %>
        </ul>
      </div>
    </footer>
  </body>
</html>